-- Structure of the database

CREATE TABLE ALBUM (
    IDAlbum INTEGER AUTO_INCREMENT NOT NULL,
    NomAlbum VARCHAR(64) NOT NULL,
    CONSTRAINT pk_album PRIMARY KEY (IDAlbum)
) ENGINE=InnoDB;

CREATE TABLE INDIVIDU (
    IDInd INTEGER AUTO_INCREMENT NOT NULL,
    IDPere INTEGER NULL DEFAULT NULL,
    IDMere INTEGER NULL DEFAULT NULL,
    NomInd VARCHAR(32) NOT NULL,
    PrenomInd VARCHAR(32) NOT NULL,
    CONSTRAINT pk_individu PRIMARY KEY (IDInd),
    CONSTRAINT fk_pere FOREIGN KEY (IDPere) REFERENCES INDIVIDU (IDInd)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_mere FOREIGN KEY (IDMere) REFERENCES INDIVIDU (IDInd)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE EVENEMENT (
    IDEvenement INTEGER AUTO_INCREMENT NOT NULL,
    LibelleEvenement VARCHAR(64) NOT NULL,
    DateEvenement BIGINT NOT NULL,
    CONSTRAINT pk_evenement PRIMARY KEY (IDEvenement)
) ENGINE=InnoDB;

CREATE TABLE PHOTO (
    IDPhoto INTEGER AUTO_INCREMENT NOT NULL,
    IDAlbum INTEGER NULL DEFAULT NULL,
    NumPage INTEGER NULL DEFAULT NULL,
    IDEvenement INTEGER NULL DEFAULT NULL,
    CONSTRAINT pk_photo PRIMARY KEY (IDPhoto),
    CONSTRAINT fk_album FOREIGN KEY (IDAlbum) REFERENCES ALBUM (IDAlbum)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_evenement FOREIGN KEY (IDEvenement) REFERENCES EVENEMENT (IDEvenement)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE APPARAIT (
    IDPhoto INTEGER AUTO_INCREMENT NOT NULL,
    IDInd INTEGER NOT NULL,
    CONSTRAINT pk_apparait PRIMARY KEY (IDPhoto),
    CONSTRAINT fk_ind FOREIGN KEY (IDInd) REFERENCES INDIVIDU (IDInd)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

INSERT INTO ALBUM (IDAlbum, NomAlbum) VALUES
(1, 'Anniv 18 ans Tristan'),
(2, 'Mariage Pop'),
(3, 'Gazette tata D');

INSERT INTO EVENEMENT (IDEvenement, LibelleEvenement, DateEvenement) VALUES
(1, 'Anniversaires Tristan', '2022-02-21'),
(2, 'Mariages', '2006-05-10'),
(3, 'Goutte chez Dédé', '2023-02-10'),
(4, 'Visite distillerie', '2019-07-18');

INSERT INTO INDIVIDU (IDInd, IDPere, IDMere, NomInd, PrenomInd) VALUES
(1, NULL, NULL, 'AMIOTTE-SUCHET', 'Gérard'),
(2, NULL, NULL, 'AMIOTTE-SUCHET', 'Jeanine'),
(3, 1, 2, 'AMIOTTE-SUCHET', 'Laurent'),
(4, 1, 2, 'AMIOTTE-SUCHET', 'Jean'),
(5, NULL, NULL, 'SAUGE', 'Ingrid'),
(7, 3, 5, 'AMIOTTE-SUCHET', 'Tristan'),
(8, NULL, NULL, 'DESTOMBE', 'Christelle'),
(9, 3, 5, 'AMIOTTE-SUCHET', 'Laël'),
(10, 4, 8, 'AMIOTTE-SUCHET', 'Jeanne');